transactions:
    pattern: /transactions
    defaults: { _controller: SinsTransactionBundle:Default:index }

transactions_debit:
    pattern: /transactions/debit
    defaults: { _controller: SinsTransactionBundle:Default:showDebitRecords }

transactions_credit:
    pattern: /transactions/credit
    defaults: { _controller: SinsTransactionBundle:Default:showCreditRecords }

transactions_add:
    pattern: /transaction/add
    defaults: { _controller: SinsTransactionRecordBundle:Default:new }
